openapi: 3.0.0
info:
 title: Book API
 version: 1.0.0
 description: API for managing books
servers:
 - url: http://localhost:3000/api/v1
   description: Development server

paths:
 /books:
   get:
     summary: Get a list of books
     operationId: getBooks
     responses:
       '200':
         description: A list of books
         content:
           application/json:
             schema:
               type: array
               items:
                 $ref: '#/components/schemas/Book'
   post:
     summary: Add a new book
     operationId: addNewBook
     requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/Book'
     responses:
       '201':
         description: Book created
 /books/{isbn}:
   get:
     summary: Get a book by ISBN
     operationId: getBookByISBN
     parameters:
       - in: path
         name: isbn
         required: true
         schema:
           type: string
     responses:
       '200':
         description: A single book
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Book'
       '404':
         description: Book not found
   put:
     summary: Update a book by ISBN
     operationId: updateBookByISBN
     parameters:
       - in: path
         name: isbn
         required: true
         schema:
           type: string
     requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/Book'
     responses:
       '200':
         description: Book updated
       '404':
         description: Book not found
   delete:
     summary: Delete a book by ISBN
     operationId: deleteBookByISBN
     parameters:
       - in: path
         name: isbn
         required: true
         schema:
           type: string
     responses:
       '204':
         description: Book deleted

components:
 schemas:
   Book:
     type: object
     required:
       - isbn
       - title
       - author
       - publish_date
       - publisher
       - numOfPages
     properties:
       isbn:
         type: string
         example: "9781593275846"
       title:
         type: string
         example: "Eloquent JavaScript, Second Edition"
       author:
         type: string
         example: "Marijn Haverbeke"
       publish_date:
         type: string
         format: date
         example: "2014-12-14"
       publisher:
         type: string
         example: "No Starch Press"
       numOfPages:
         type: integer
         example: 472