openapi: 3.0.0
info:
  title: Books API
  description: API for managing book information
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Development server

components:
  schemas:
    Book:
      type: object
      required:
        - isbn
        - title
        - author
        - publish_date
        - publisher
        - numOfPages
      properties:
        isbn:
          type: string
          example: "9781593275846"
        title:
          type: string
          example: "Eloquent JavaScript, Second Edition"
        author:
          type: string
          example: "Marijn Haverbeke"
        publish_date:
          type: string
          format: date
          example: "2014-12-14"
        publisher:
          type: string
          example: "No Starch Press"
        numOfPages:
          type: integer
          example: 472

paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books/{isbn}:
    parameters:
      - name: isbn
        in: path
        required: true
        schema:
          type: string
    
    get:
      summary: Get book by ISBN
      responses:
        '200':
          description: Book found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
    
    put:
      summary: Update a book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
    
    delete:
      summary: Delete a book
      responses:
        '204':
          description: Book deleted successfully
        '404':
          description: Book not found